#    ██████╗ ██████╗ ██████╗ ███╗  ██╗██████╗       ██████╗  █████╗  █████╗ ███████╗ ██████╗
#    ██╔══██╗██╔══██╗██╔══██╗████╗ ██║██╔══██╗      ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔════╝
#    ██████╔╝██████╔╝██║  ██║██╔██╗██║██║  ██║█████╗██████╔╝███████║██║  ╚═╝█████╗  ╚█████╗
#    ██╔══██╗██╔═══╝ ██║  ██║██║╚████║██║  ██║╚════╝██╔══██╗██╔══██║██║  ██╗██╔══╝   ╚═══██╗
#    ██║  ██║██║     ██████╔╝██║ ╚███║██████╔╝      ██║  ██║██║  ██║╚█████╔╝███████╗██████╔╝
#    ╚═╝  ╚═╝╚═╝     ╚═════╝ ╚═╝  ╚══╝╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚════╝ ╚══════╝╚═════╝

MySQL:
  username: ''
  password: ''
  database: ''
  host: ''
  port: