#   ██████╗  █████╗  █████╗ ███████╗ ██████╗
#   ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔════╝
#   ██████╔╝███████║██║  ╚═╝█████╗  ╚█████╗
#   ██╔══██╗██╔══██║██║  ██╗██╔══╝   ╚═══██╗
#   ██║  ██║██║  ██║╚█████╔╝███████╗██████╔╝
#   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚════╝ ╚══════╝╚═════╝

mysql:
  username: ''
  password: ''
  database: ''
  host: ''
  port: